language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: qvxtgT5LaLp52fAOjz/WIRs6YM2qZ0Lzp/HaSSlvj1/YPgh2t80IOu31y2jHgnWxZDoUDdhbims/s1Wmn6wgE9jXW8MBipKVzYsd69BPgXGgdl3SssDhOCDBQeUbAtZn02N2fTvtdX68cgwgkZDiHfwjV48KTX3ELbTpMtlo7P1UmlQVGe/qFzO2rK8AxvBSHozuIUwPVbjQ8y8hqzlkREjIrRK5IeKM0jaC8EhEpvEF2AtkMYr9WJuc5zMC2iV9VIEWIcyLP5gmRQGOJ8gmgtpIKPPOyEDdEos37mYouh0/s3Sdmnrgh4KLFq5fFzufLNd9GhoJqB27/bKpqwejNC+XRxUO5+wVn1AD26+GbBxvGvqhkCbwcS9SiARPkOFbnBpca291yMPoM/h75Tid+bdnE8Rz0tFyjHoq1Ikf0C41mUhkGguZakCPnKtNqS1+VsJY3aUaTG7zqWAZvVR17Q2DuMR0yyEOA9E0NmkffmRMG85oZotwlxyWwKIhxTGZNsRD3ujiXccK9YaLfGddg/SlkvZkR5uIEzElH/Fak0pB1Nyv8gbNm1mlUhZmm3QXHVUtPTZM8QqSHm8PKwNA52eiMGX/1IRKdl01d58io7F7pOX/wB5d46oqx3qXeckzoETS6R05NY4mRSCVbnPxW7tyMcqZwu/qcj5GBTT9bmk=
