language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: dryKJNwAQvip8EwGHcbzXDRDlMsezbh5KSUAoLU/p6M6jH3GNDYHRLI5iLbhwS0vfpBdqAJmisqM5Y8KdKDWCtim23ehwS30jjamngGy5+EI6piJFLm4qcv3g/ONIc91e9oSqhLx1u1yCMJ1dzTbvceJRAQZloHlOY68b8al6lgnlESuvNsm7CZb6qk0NBOqzZd42bCcQG8t5D1IBJ2Afu1wbKJ7BIJq7HPcVsioDCsTKWF8/6QF2HwjwjcmlHOT1KLZlQlqrajeXYLqdFnUigBHg11l8sjg+KpzUOA8IuBB5ViHZToTy0F58eO9wC6dA9lT3YVybBzxB0AZtFhkL8v6ypU1hXTq1Odh+4ViLb+PCH22o44WUvGhYQGXFQeTyzRirA32QIUMm0n5r0idjg/beY/ijz25FnftGrIf1KrjNP+vvbmdIvCyByTSIqlKzaDSRCV0CmjyroWhbk6yNZ/vpDJHgV23M1P/CbCYMA84dh6Ifu0hYdJdC+/pW7nv7pHjugqiP5VjDU1xcrgq7lRuq2WaoJHhtVOoGmizyePMraJC+Of7vVjRCXdVXiRGEz/Dl90qLdjo3WJH9SWr60EGHWtWRi54t89SXqd5cb6OiRWOIyKsPM/CUsDMZqYId67esyq2WVZ/7tJRl9KFS8FbSmf97TExyETlXXp/owE=
