language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: nPggD6UIfoIGcpzvGiN7aW+fppyWTfVDXjtLDSiHhnrnLbMTHSUHM0tRPwEvIna8qCCFpZR4hWEAMSZwu2YbkvyaBfFd2mt/EAbrYbAVyH7hbPnt+KA1hb2/ZsBZx4nq5GqsOY1qEzB4JZNKhdsy/Brx8wdqjotiuwPkoMm1TUBMR2zf5Di5zMlhLB0fPbd8N3J1pjiYgCaPT2ePiamytLsbCDZco3ZIBzKzbY89ivL1RlqkKgkcgqad4aIsPAq8t+AsdomvBG+236QiMsUXZ0/5rSEyqRJ6GwFqGHnUtXrMQ+6ZJZc8GD2jw4jv0DJwnyy6RVakhW5g6imWGpev6AqLv2ZeIwRrOwb7sLVvvYRomJ/S1nwSoVCVpHqaspnzTuZWY6dD+bWpZ+m2iTp6hbnE4gqmxrlcAVWn6iEGuLeq3trkFG44uQ/zTdCbimmWSR4Swrps+aTzM/Y8A3xyuEaYZ2eUQuumH5kJfh6gtbI4n8H/bWvGKFrqpVQ6a4Eiy4pTh70TXbTMjbOpYbZeCZ8OTOi3sE1VAg/neIU7i0R3ZaVink6Hs3QcgBVkLU31RR6tGTouhh0z6wPSG+/fO8lHfZlzdfAR/mV+TLBfyQqggwKAy8lPMgkVL+FV7KfGEUNECCQHDvU+oEA8fVOSJ92Q31Q0XS+raPl43mM/IEw=
